name: Playwright Tests

# Only run one at a time per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - '*'
      
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install app dependencies
        run: pnpm install

      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        env:
          VITE_NETWORK: signet
          VITE_PROXY: wss://p.mutinywallet.com
          VITE_ESPLORA: https://mutinynet.com/api
          VITE_LSP: https://signet-lsp.mutinywallet.com
          VITE_RGS: https://rgs.mutinynet.com/snapshot/
          VITE_AUTH: https://auth-staging.mutinywallet.com
          VITE_SUBSCRIPTIONS: https://subscriptions-staging.mutinywallet.com
          VITE_STORAGE: https://storage-staging.mutinywallet.com/v2
          VITE_FEEDBACK: https://feedback-staging.mutinywallet.com
          VITE_SCORER: https://scorer-staging.mutinywallet.com
          VITE_PRIMAL: https://primal-cache.mutinywallet.com/api
        run: pnpm exec playwright test --grep-invert @slow
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
